# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f46d951696e3efe5f62f75bc28bef5c30ddba77944d4ca08aab4a3c2939e37d53ade0ff375131c0c9fd35a276ee04b62aaafe8d62db06e911a7fca3f9e3431

test:
  secret_key_base: 93b31616e634112210080e3d50a72f32656b3ae55bf19f3992e08fd77c3f75883f18920c9867047b14c4a8cf4da0b861a066cc04c414579bf8353899a97854c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
